# list of all us presidents
presidents = [
        	{ 
		'name': 'George Washington',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/George_Washington',
		'took_office': '30/04/1789',
		'left_office': '4/03/1797',
		'affiliation': 'Independent ',
	},
	{ 
		'name': 'John Adams',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/John_Adams',
		'took_office': '4/03/1797',
		'left_office': '4/03/1801',
		'affiliation': 'Federalist ',
	},
	{ 
		'name': 'Thomas Jefferson',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Thomas_Jefferson',
		'took_office': '4/03/1801',
		'left_office': '4/03/1809',
		'affiliation': 'Democratic-Republican ',
	},
	{ 
		'name': 'James Madison',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/James_Madison',
		'took_office': '4/03/1809',
		'left_office': '4/03/1817',
		'affiliation': 'Democratic-Republican ',
	},
	{ 
		'name': 'James Monroe',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/James_Monroe',
		'took_office': '4/03/1817',
		'left_office': '4/03/1825',
		'affiliation': 'Democratic-Republican ',
	},
	{ 
		'name': 'John Quincy Adams',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/John_Quincy_Adams',
		'took_office': '4/03/1825',
		'left_office': '4/03/1829',
		'affiliation': 'Democratic-Republican/National Republican ',
	},
	{ 
		'name': 'Andrew Jackson',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Andrew_Jackson',
		'took_office': '4/03/1829',
		'left_office': '4/03/1837',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'Martin Van Buren',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Martin_Van_Buren',
		'took_office': '4/03/1837',
		'left_office': '4/03/1841',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'William Henry Harrison',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/William_Henry_Harrison',
		'took_office': '4/03/1841',
		'left_office': '4/04/1841',
		'affiliation': 'Whig',
	},
	{ 
		'name': 'John Tyler',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/John_Tyler',
		'took_office': '4/04/1841',
		'left_office': '4/03/1845',
		'affiliation': 'Whig',
	},
	{ 
		'name': 'James K. Polk',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/James_K._Polk',
		'took_office': '4/03/1845',
		'left_office': '4/03/1849',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'Zachary Taylor',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Zachary_Taylor',
		'took_office': '4/03/1849',
		'left_office': '9/07/1850',
		'affiliation': 'Whig',
	},
	{ 
		'name': 'Millard Fillmore',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Millard_Fillmore',
		'took_office': '9/07/1850',
		'left_office': '4/03/1853',
		'affiliation': 'Whig',
	},
	{ 
		'name': 'Franklin Pierce',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Franklin_Pierce',
		'took_office': '4/03/1853',
		'left_office': '4/03/1857',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'James Buchanan',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/James_Buchanan',
		'took_office': '4/03/1857',
		'left_office': '4/03/1861',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'Abraham Lincoln',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Abraham_Lincoln',
		'took_office': '4/03/1861',
		'left_office': '15/04/1865',
		'affiliation': 'Republican/National Union',
	},
	{ 
		'name': 'Andrew Johnson',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Andrew_Johnson',
		'took_office': '15/04/1865',
		'left_office': '4/03/1869',
		'affiliation': 'Democratic/National Union',
	},
	{ 
		'name': 'Ulysses S. Grant',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Ulysses_S._Grant',
		'took_office': '4/03/1869',
		'left_office': '4/03/1877',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Rutherford B. Hayes',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Rutherford_B._Hayes',
		'took_office': '4/03/1877',
		'left_office': '4/03/1881',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'James A. Garfield',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/James_A._Garfield',
		'took_office': '4/03/1881',
		'left_office': '19/09/1881',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Chester A. Arthur',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Chester_A._Arthur',
		'took_office': '19/09/1881',
		'left_office': '4/03/1885',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Grover Cleveland',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Grover_Cleveland',
		'took_office': '4/03/1885',
		'left_office': '4/03/1889',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'Benjamin Harrison',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Benjamin_Harrison',
		'took_office': '4/03/1889',
		'left_office': '4/03/1893',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Grover Cleveland (2nd term)',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Grover_Cleveland',
		'took_office': '4/03/1893',
		'left_office': '4/03/1897',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'William McKinley',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/William_McKinley',
		'took_office': '4/03/1897',
		'left_office': '14/9/1901',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Theodore Roosevelt',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Theodore_Roosevelt',
		'took_office': '14/9/1901',
		'left_office': '4/3/1909',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'William Howard Taft',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/William_Howard_Taft',
		'took_office': '4/3/1909',
		'left_office': '4/03/1913',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Woodrow Wilson',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Woodrow_Wilson',
		'took_office': '4/03/1913',
		'left_office': '4/03/1921',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'Warren G. Harding',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Warren_G._Harding',
		'took_office': '4/03/1921',
		'left_office': '2/8/1923',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Calvin Coolidge',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Calvin_Coolidge',
		'took_office': '2/8/1923',
		'left_office': '4/03/1929',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Herbert Hoover',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Herbert_Hoover',
		'took_office': '4/03/1929',
		'left_office': '4/03/1933',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Franklin D. Roosevelt',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Franklin_D._Roosevelt',
		'took_office': '4/03/1933',
		'left_office': '12/4/1945',
		'affiliation': 'Democratic',
	},
	{ 
		'name': 'Harry S. Truman',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Harry_S._Truman',
		'took_office': '12/4/1945',
		'left_office': '20/01/1953',
		'affiliation': 'Democratic',
	},
	{ 
		'name': 'Dwight D. Eisenhower',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Dwight_D._Eisenhower',
		'took_office': '20/01/1953',
		'left_office': '20/01/1961',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'John F. Kennedy',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/John_F._Kennedy',
		'took_office': '20/01/1961',
		'left_office': '22/11/1963',
		'affiliation': 'Democratic',
	},
	{ 
		'name': 'Lyndon B. Johnson',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Lyndon_B._Johnson',
		'took_office': '22/11/1963',
		'left_office': '20/1/1969',
		'affiliation': 'Democratic',
	},
	{ 
		'name': 'Richard Nixon',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Richard_Nixon',
		'took_office': '20/1/1969',
		'left_office': '9/8/1974',
		'affiliation': 'Republican',
	},
	{ 
		'name': 'Gerald Ford',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Gerald_Ford',
		'took_office': '9/8/1974',
		'left_office': '20/01/1977',
		'affiliation': 'Republican',
	},
	{ 
		'name': 'Jimmy Carter',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Jimmy_Carter',
		'took_office': '20/01/1977',
		'left_office': '20/01/1981',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'Ronald Reagan',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Ronald_Reagan',
		'took_office': '20/01/1981',
		'left_office': '20/01/1989',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'George H. W. Bush',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/George_H._W._Bush',
		'took_office': '20/01/1989',
		'left_office': '20/01/1993',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Bill Clinton',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Bill_Clinton',
		'took_office': '20/01/1993',
		'left_office': '20/01/2001',
		'affiliation': 'Democratic ',
	},
	{ 
		'name': 'George W. Bush',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/George_W._Bush',
		'took_office': '20/01/2001',
		'left_office': '20/01/2009',
		'affiliation': 'Republican ',
	},
	{ 
		'name': 'Barack Obama',
		'wikipedia_url': 'http://en.wikipedia.org/wiki/Barack_Obama',
		'took_office': '20/01/2009',
		'left_office': '20/01/2017',
		'affiliation': '  Democratic   ',
	},
	{ 
		'name': 'Donald Trump',
		'wikipedia_url': 'https://en.wikipedia.org/wiki/Donald_Trump',
		'took_office': '20/01/2017',
		'left_office': 'Incumbent',
		'affiliation': ' Republican',
	},
]